name: Swift

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

jobs:
  build:
    name: Build, Test, Lint
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,name=iPad Pro (12.9-inch) (3rd generation),OS=13.3"]

    steps:
    - uses: actions/checkout@v2
    - name: Install SwiftLint
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
      run: brew install swiftlint
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: Hive2D/Pods
        key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/Hive2D/Podfile.lock') }}
        restore-keys: |
          ${{ runner.OS }}-pods-cache-
    - name: Install dependencies
      run: |
        cd Hive2D
        pod install
    - name: Build
      run: |
        cd Hive2D
        xcodebuild build-for-testing -workspace Hive2D.xcworkspace -scheme Hive2D -destination "${destination}"
      env: 
         destination: ${{ matrix.destination }}
    - name: Run tests
      run: |
        cd Hive2D
        xcodebuild test-without-building -workspace Hive2D.xcworkspace -scheme Hive2D -destination "${destination}"
      env: 
         destination: ${{ matrix.destination }}
    - name: Run SwiftLint
      run: |
        cd Hive2D
        swiftlint lint --reporter github-actions-logging
